### ISSUE TITLE
Search Result page: The layout has 3 columns but paginates after 10 items, this leaves a blank space at the last row. 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#12]
**It seems better to paginate after 9 items since the layout has 3 columns.**

![image](https://cloud.githubusercontent.com/assets/12888048/19510119/68524676-9614-11e6-80fe-f945d99343d9.png)

**Comment by emmixaustralia** [comment]
What sample "search term" did you use?
