### ISSUE TITLE
General: External link open in the current (same) tab. An external link should open in a new tab.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#17]
Affected Pages:

**Core Values**
URL: http://jenmanlive.emmixhosting.com.au/the-core-values-of-approved/
![image](https://cloud.githubusercontent.com/assets/12888048/19513921/4bda60fe-9624-11e6-927f-63b6ee4b019e.png)

**Books**
URL: http://jenmanlive.emmixhosting.com.au/books/success-takes-character/
![image](https://cloud.githubusercontent.com/assets/12888048/19516601/45d5aed8-962f-11e6-8fac-9ab2b6ad3fbe.png)

**Don't Sign Anything**
URL: http://jenmanlive.emmixhosting.com.au/books/dont-sign-anything/
![image](https://cloud.githubusercontent.com/assets/12888048/19516616/5aef0454-962f-11e6-8476-1b3ffb67997b.png)

**Help Home Sellers**
URL: http://jenmanlive.emmixhosting.com.au/books/help-home-sellers/
![image](https://cloud.githubusercontent.com/assets/12888048/19516675/9ca4afb6-962f-11e6-8a25-0283d4ad759c.png)

**The Inside Secrets of Real Estate**
URL: http://jenmanlive.emmixhosting.com.au/books/inside-secrets-real-estate/
![image](https://cloud.githubusercontent.com/assets/12888048/19516697/bfd5547c-962f-11e6-8ff6-673bf0248a76.png)

**Real Estate Mistakes**
URL: http://jenmanlive.emmixhosting.com.au/books/real-estate-mistakes/
![image](https://cloud.githubusercontent.com/assets/12888048/19516713/e2311bf0-962f-11e6-8649-d8d9cb64c86c.png)

Real Estate Without Agents
URL: http://jenmanlive.emmixhosting.com.au/real-estate-without-agents/
![image](https://cloud.githubusercontent.com/assets/12888048/19516774/36301d8c-9630-11e6-85b7-a9a4aa75c2d6.png)

**Real Estate Mistakes**
URL: http://jenmanlive.emmixhosting.com.au/remistakes/
![image](https://cloud.githubusercontent.com/assets/12888048/19519488/cf469d9e-963e-11e6-86ba-b385c0f9a999.png)

**Comment by emmixaustralia** [comment]
Inherited content issue.
