### ISSUE TITLE
Find an Agent: After successful submission of the form, the form instruction still displayed in the front end. It should be hidden since there's no form below after successful submission.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#20]
URL: http://jenmanlive.emmixhosting.com.au/find-an-agent-result/

![image](https://cloud.githubusercontent.com/assets/12888048/19515911/1584642a-962c-11e6-943e-f557725f6bc6.png)

**Comment by emmixaustralia** [comment]
Forms will be switched to use a dedicated Thank you page upon successful send. This item is therefore N/A.
