### ISSUE TITLE
Download Modal Form: Text input color is red.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#21]
URL:
http://jenmanlive.emmixhosting.com.au/18-worst-mistakes-made-by-homesellers-the-solutions/
http://jenmanlive.emmixhosting.com.au/the-13-worst-mistakes-made-by-homebuyers/

To Replicate:
1. Go to any of the above links.
2. Click download or get a free copy  link
3. Click submit button to display error message
4. Input text in the field(s).

![image](https://cloud.githubusercontent.com/assets/12888048/19517380/7d57fba0-9633-11e6-9754-0b847cd9817b.png)

**Comment by emmixaustralia** [comment]
This is not an issue of the website. That popup is generated by/from LeadPages -- a 3rd party tool the client is using. We cannot do anything about that. We inherited this existing site with a lot of content issues from the client.
