### ISSUE TITLE
"BOOKS" was not included in Real Estate Without Agents breadcrumbs trail.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#22]
URL: http://jenmanlive.emmixhosting.com.au/real-estate-without-agents/

![image](https://cloud.githubusercontent.com/assets/12888048/19517029/6d873954-9631-11e6-8a3a-cafaf6ac2e01.png)

**Comment by emmixaustralia** [comment]
It was missing the Books Parent page. Fixed now.
