### ISSUE TITLE
General: The site saves inputted data after successful submission. If possible clear the fields after submission.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#23]
URL:
http://jenmanlive.emmixhosting.com.au/18-worst-mistakes-made-by-homesellers-the-solutions/
http://jenmanlive.emmixhosting.com.au/the-13-worst-mistakes-made-by-homebuyers/

![image](https://cloud.githubusercontent.com/assets/12888048/19517503/2b2d9e74-9634-11e6-9eba-c3ca10cef254.png)

**Comment by emmixaustralia** [comment]
That popup is driven by client's 3rd party tool, LeadPages. We can't change that functionality.
