### ISSUE TITLE
Why is it that the Thank You page is an external link. Should the site have its own thank you page?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#24]
After submission of the modal form "Thinking of buying?", it will redirect to:
https://helpers.leadpages.co/18-mistakes-thank-you-jenman/
https://my.leadpages.net/thank-you/

![image](https://cloud.githubusercontent.com/assets/12888048/19517638/00e63288-9635-11e6-911f-6a9d64f96e8d.png)

**Comment by emmixaustralia** [comment]
This is a feature using LeadPages external 3rd party system, it's not in our control.
