### ISSUE TITLE
The "Home" link redirect to a different site. Should it go back to its own homepage?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#25]
URL:
http://jenmanlive.emmixhosting.com.au/18-worst-mistakes-made-by-homesellers-the-solutions/

To Replicate:
1. Click the URL above.
2. Click the download link and complete the form, then submit.
3. Observe that after submission,it redirects to this link.
https://helpers.leadpages.co/18-mistakes-thank-you-jenman/
4. Click the "Home" hyperlink.
5. Observe that it redirect to a different site. http://jenman.com.au/

![image](https://cloud.githubusercontent.com/assets/12888048/19517684/42137af4-9635-11e6-9d88-962abe902511.png)

**Comment by emmixaustralia** [comment]
That is on the exernal LeadPages site.. it is not part of the website (note.. leadpages in the URL). I cannot change that. However when jenmanlive.emmixhosting.com.au goes live it will be jenman.com.au so the client's LeadPages home button will be ok.
