### ISSUE TITLE
Contact: Slug and page title is different. It should be the same

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#29]
![image](https://cloud.githubusercontent.com/assets/12888048/19518177/5921fefc-9638-11e6-889d-ebfc565ac4f3.png)

**Comment by emmixaustralia** [comment]
We have never seen this noted as a bug before. 

The /contact-us/ slug is used in a lot of places throughout this clients site.. they have 300 posts/pages. We need to leave the slug the same even though we have changed the page title/menu item.
