### ISSUE TITLE
Header: Please remove unnecessary sub-menus.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#3]
**Articles** menu
![image](https://cloud.githubusercontent.com/assets/12888048/19507678/1ed734d2-9607-11e6-858c-a30219b0a1cf.png)

**Books** menu
![image](https://cloud.githubusercontent.com/assets/12888048/19507834/e83fcba4-9607-11e6-9611-aa9feb5e9a82.png)
![image](https://cloud.githubusercontent.com/assets/12888048/19507837/eb380718-9607-11e6-80ec-9471905cefdc.png)

**Comment by emmixaustralia** [comment]
These have already been removed, please make sure you're testing the right website URL http://jenmanlive.emmixhosting.com.au/
