### ISSUE TITLE
Grid list: There is huge space gap between items in the grid at 642-1025px.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Jenman-Group#36]
![image](https://cloud.githubusercontent.com/assets/11186313/19545902/f7e3974c-96bc-11e6-86a9-054ee66008d3.png)

![image](https://cloud.githubusercontent.com/assets/11186313/19545901/f3ce2ec4-96bc-11e6-80bf-39490fc0aa6a.png)

**Comment by emmixaustralia** [comment]
Fixed
