### ISSUE TITLE
A "Comments"  heading was displayed in the front-end but there's no comment form.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#37]
URL: http://jenmanlive.emmixhosting.com.au/selling-without-estate-agents-2ue-interview/

![image](https://cloud.githubusercontent.com/assets/12888048/19547304/703e9b0e-96c9-11e6-9e80-e2f836e7a53a.png)

**Comment by emmixaustralia** [comment]
Fixed
