### ISSUE TITLE
Internal links open in a new tab. It should open in the same tab

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#39]
URL:  http://jenmanlive.emmixhosting.com.au/speaking/
![image](https://cloud.githubusercontent.com/assets/12888048/19547940/e56c145c-96cd-11e6-8603-47a4b5e4e20c.png)

URL:  
http://jenmanlive.emmixhosting.com.au/ethical-concerns/
![image](https://cloud.githubusercontent.com/assets/12888048/19548155/4585b554-96cf-11e6-9d07-f9e63949c5fa.png)

Hyperlink: "contact us"
http://jenmanlive.emmixhosting.com.au/rent-buy-schemes/

**Comment by emmixaustralia** [comment]
Inherited content issues
