### ISSUE TITLE
Clarification - Sidebar: Should the search suggest be displayed as well in the sidebar search?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#4]
![image](https://cloud.githubusercontent.com/assets/12888048/19508054/94bb4182-9609-11e6-9701-f7f40aac0673.png)

**Comment by emmixaustralia** [comment]
If you're browsing http://jenmanlive.emmixhosting.com.au/ it does show the auto suggest on the sidebar search widget.

**Comment by romatitan** [comment]
On the **sidebar search**, it didn't display  the auto suggest.

**Comment by emmixaustralia** [comment]
Please re check all of your feedback items. You are browsing the wrong website.

You need to browse http://jenmanlive.emmixhosting.com.au/

This is working on this website
