### ISSUE TITLE
General: External link should open in a new tab

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#42]
**Please check hyperlinks.**

Hyperlinks: "Click here to order", "Order", "Order Online", "Order Manual Online", and images
http://jenmanlive.emmixhosting.com.au/publications/

Hyperlink: "charity"
http://jenmanlive.emmixhosting.com.au/ethical-concerns/

Hyperlink: "order now", "CLICK HERE"
http://jenmanlive.emmixhosting.com.au/remistakes-intro2/

Hyperlink: "Jenman APPROVED accreditation"
http://jenmanlive.emmixhosting.com.au/cold-august-night/

Hyperlink: "Order"
http://jenmanlive.emmixhosting.com.au/dsa/

Hyperlink: "This is Money UK"
http://jenmanlive.emmixhosting.com.au/gazumping-be-aware/

Hyperlink: "Harris Partners"
http://http://jenmanlive.emmixhosting.com.au/sellers-dont-buy-first/

Hyperlink: "Hotspotting:
http://jenmanlive.emmixhosting.com.au/the-humble-agent/

Hyperlink: " Real Estate Monitors"
http://jenmanlive.emmixhosting.com.au/the-auction-run-around/

Hyperlink: "OZprivatesale.com.au", "NSW Department of Fair Trading"
http://jenmanlive.emmixhosting.com.au/just-a-little-rip-off/

Hyperlink: "Find an APPROVED Jenman agent", "website", " Koops Martin Group", 
http://jenmanlive.emmixhosting.com.au/our-values/

Hyperlink: "Crikey", "trial subscription", "businessspectator.com.au", "Crikey reported", " ASIC dropped proceedings"
http://jenmanlive.emmixhosting.com.au/lkm-capital-limited/

Hyperlink: "www.finning.com.au" 
http://jenmanlive.emmixhosting.com.au/fees-for-landlords/

Hyperlink: "Millionaire make believe"
http://jenmanlive.emmixhosting.com.au/millionaire-challenge-deep-hole/

Hyperlink: "Travis Morien's web site."
http://jenmanlive.emmixhosting.com.au/stayaway-from-henry-kaye/

Hyperlink: "visit the ASIC web site."
http://jenmanlive.emmixhosting.com.au/knock-knock/

**Comment by emmixaustralia** [comment]
Inherited content issues
