### ISSUE TITLE
Approved Search Post: If possible implement the auto suggest on this page search field

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#45]
URL: http://jenmanlive.emmixhosting.com.au/approved-search-post/

![image](https://cloud.githubusercontent.com/assets/12888048/19548287/3a729af0-96d0-11e6-883c-edca6baebdf6.png)

**Comment by emmixaustralia** [comment]
http://jenmanlive.emmixhosting.com.au/find-an-agent/

**Comment by emmixaustralia** [comment]
Old client page. Page redirected to new one http://jenmanlive.emmixhosting.com.au/find-an-agent/
