### ISSUE TITLE
Approved Search Post: Kindly implement the same flat style for the button

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#46]
URL: http://jenmanlive.emmixhosting.com.au/approved-search-post/

![image](https://cloud.githubusercontent.com/assets/12888048/19548333/7c102680-96d0-11e6-980a-107b62adf4b0.png)

**Comment by emmixaustralia** [comment]
Old client page. Page removed/redirected to new search page http://jenmanlive.emmixhosting.com.au/find-an-agent/
