### ISSUE TITLE
Approved Search Post: Search is not working as expected. After clicking the "Find" button, nothing happened

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#47]
URL: http://jenmanlive.emmixhosting.com.au/approved-search-post/

![image](https://cloud.githubusercontent.com/assets/12888048/19548374/adff2646-96d0-11e6-88f9-45f0871d3588.png)

**Comment by emmixaustralia** [comment]
Old inherited content, page to be archived/removed.
