### ISSUE TITLE
Sidebar - Search: Search is not working as expected. It only redirects to "Find An Agent" even there's an item or word(s) to find.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#5]
![image](https://cloud.githubusercontent.com/assets/12888048/19508181/537242f6-960a-11e6-9e61-cd84c19b1eec.png)

**Comment by emmixaustralia** [comment]
This is working.. please make sure you are testing the correct website http://jenmanlive.emmixhosting.com.au/
