### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#51]
URL: http://jenmanlive.emmixhosting.com.au/8-reasons-consider-jenman-approved-agent-selling-property/

![image](https://cloud.githubusercontent.com/assets/12888048/19549184/725509a8-96d5-11e6-9fd1-1f9cee9424e1.png)

Hyperlink: "Lawyers Real Estate Pty Ltd"
http://jenmanlive.emmixhosting.com.au/conveyancing-bribes/

Hyperlink: "THE SECRETS OF HANS JAKOBI"
http://jenmanlive.emmixhosting.com.au/the-47-pitch/

**Comment by emmixaustralia** [comment]
Inherited content issue.
