### ISSUE TITLE
A hyperlink open the same page in a new tab

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#53]
Hyperlink: "grab the grant quick", "Finding Today’s Worst Investment"
http://jenmanlive.emmixhosting.com.au/buy-not-buy/

![image](https://cloud.githubusercontent.com/assets/12888048/19549428/df4aeafe-96d6-11e6-9523-c111279ce942.png)

**Comment by emmixaustralia** [comment]
Inherited content issue.
