### ISSUE TITLE
Contact - details: Forms in the Comments, Complaints and Your Story tabs aren't visible.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Jenman-Group#54]
![image](https://cloud.githubusercontent.com/assets/11186313/19549578/ad46dac6-96d7-11e6-8ecf-df510b98dcae.png)
![image](https://cloud.githubusercontent.com/assets/11186313/19549602/ca7add22-96d7-11e6-8857-94ad61299216.png)
![image](https://cloud.githubusercontent.com/assets/11186313/19552757/ca7b5f98-96e3-11e6-8cae-2bec65370e31.png)

**Comment by emmixaustralia** [comment]
Inherited content issue, we did not set up. New contact page we created is http://jenmanlive.emmixhosting.com.au/contact-us/
