### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#55]
URL: http://jenmanlive.emmixhosting.com.au/neil-jenman-answers-wrap-questions/

**Hyperlinks:**
THE WRAPPING DEBATE
BATTLING BUYERS BEWARESHARK ALARM
Neil Jenman on Wraps
The Story of Erwin
Consumer Lawyer on Wraps
THE MILLIONAIRE CHALLENGE

![image](https://cloud.githubusercontent.com/assets/12888048/19549947/a0693ea0-96d9-11e6-83de-eed247b762fa.png)

**Comment by emmixaustralia** [comment]
Inherited content issue.
