### ISSUE TITLE
Henry Kaye Victims: Hyperlink is linked to the old site.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Jenman-Group#65]
http://jenmanlive.emmixhosting.com.au/henry-kaye-victims/
![image](https://cloud.githubusercontent.com/assets/11186313/19553420/d63e3ec4-96e6-11e6-9030-ca1ac4f312ae.png)

**Comment by emmixaustralia** [comment]
Inherited content issue.
