### ISSUE TITLE
Different favicon was displayed in other browsers

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#68]
**Chrome,Firefox,Opera**
![image](https://cloud.githubusercontent.com/assets/12888048/19554149/dc5e8220-96e9-11e6-965c-5eb40a9306b6.png)

**Microsoft Edge, IE11**
![image](https://cloud.githubusercontent.com/assets/12888048/19554150/debdd016-96e9-11e6-9fcb-c2f647854ae7.png)

**Comment by emmixaustralia** [comment]
Fixed
