### ISSUE TITLE
Header: Dead link for social media icons

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Jenman-Group#7]
![image](https://cloud.githubusercontent.com/assets/12888048/19508633/ce906a2e-960c-11e6-898c-e04e02e72efa.png)

**Comment by emmixaustralia** [comment]
Please make sure you are still on http://jenmanlive.emmixhosting.com.au/

You seem to be browsing the old development site (http://jenman.emmixhosting.com.au/) before we migrated and merged with the client's content.
